/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HolderInfo = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const AssetSymbol = IDL.Text;
export const PriceResultNat = IDL.Variant({
  'completed' : IDL.Record({ 'value' : IDL.Nat }),
});

export const idlService = IDL.Service({
  'getHolderAddress' : IDL.Func([IDL.Principal], [HolderInfo], []),
  'getUniqueHolderAddresses' : IDL.Func([], [IDL.Vec(HolderInfo)], []),
  'swapTokens' : IDL.Func(
      [AssetSymbol, AssetSymbol, IDL.Nat],
      [PriceResultNat],
      [],
    ),
  'validateAddress' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HolderInfo = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const AssetSymbol = IDL.Text;
  const PriceResultNat = IDL.Variant({
    'completed' : IDL.Record({ 'value' : IDL.Nat }),
  });
  
  return IDL.Service({
    'getHolderAddress' : IDL.Func([IDL.Principal], [HolderInfo], []),
    'getUniqueHolderAddresses' : IDL.Func([], [IDL.Vec(HolderInfo)], []),
    'swapTokens' : IDL.Func(
        [AssetSymbol, AssetSymbol, IDL.Nat],
        [PriceResultNat],
        [],
      ),
    'validateAddress' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };