/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetSymbol = string;
export interface HolderInfo {
  'principal' : Principal,
  'balance' : bigint,
  'percentage' : number,
}
export type PriceResultNat = { 'completed' : { 'value' : bigint } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getHolderAddress' : ActorMethod<[Principal], HolderInfo>,
  'getMetrics' : ActorMethod<
    [],
    { 'marketCap' : number, 'volume24h' : number, 'price' : number }
  >,
  'getUniqueHolderAddresses' : ActorMethod<[], Array<HolderInfo>>,
  'swapTokens' : ActorMethod<
    [AssetSymbol, AssetSymbol, bigint],
    PriceResultNat
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'validateAddress' : ActorMethod<[Uint8Array], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];