/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    memo: string;
    operation: TransactionOperation;
    timestamp: bigint;
    index: bigint;
}
export interface BurnOperation {
    from: Uint8Array;
    amount: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type TransactionOperation = {
    __kind__: "burn";
    burn: BurnOperation;
} | {
    __kind__: "mint";
    mint: MintOperation;
} | {
    __kind__: "transfer";
    transfer: TransferOperation;
};
export interface Icrc1TransactionWithId {
    id: bigint;
    transaction: Icrc1Transaction;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MintOperation {
    to: Uint8Array;
    amount: bigint;
}
export interface Icrc1Transaction {
    to?: Uint8Array;
    fee?: bigint;
    from?: Uint8Array;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}
export interface TransactionWithDetail {
    transaction_type: string;
    transaction: Transaction;
    network: string;
    amount_adjusted: number;
    transfer_to?: Principal;
    value_usd: number;
    augmented_memo: string;
    amount: bigint;
    transfer_from?: Principal;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TransferOperation {
    to: Uint8Array;
    fee: bigint;
    from: Uint8Array;
    amount: bigint;
}
export interface backendInterface {
    cacheIcTransaction(_transaction: Icrc1TransactionWithId): Promise<boolean>;
    getAllIcTransactions(_maxResults: bigint, _includeMarkets: boolean, _sortField: string, _search: string, _reverse: boolean): Promise<Array<Icrc1TransactionWithId>>;
    getRecentTransactions(limit: bigint, offset: bigint): Promise<Array<TransactionWithDetail>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { BurnOperation as _BurnOperation, Icrc1Transaction as _Icrc1Transaction, Icrc1TransactionWithId as _Icrc1TransactionWithId, MintOperation as _MintOperation, Transaction as _Transaction, TransactionOperation as _TransactionOperation, TransactionWithDetail as _TransactionWithDetail, TransferOperation as _TransferOperation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cacheIcTransaction(arg0: Icrc1TransactionWithId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cacheIcTransaction(to_candid_Icrc1TransactionWithId_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cacheIcTransaction(to_candid_Icrc1TransactionWithId_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllIcTransactions(arg0: bigint, arg1: boolean, arg2: string, arg3: string, arg4: boolean): Promise<Array<Icrc1TransactionWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIcTransactions(arg0, arg1, arg2, arg3, arg4);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIcTransactions(arg0, arg1, arg2, arg3, arg4);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentTransactions(arg0: bigint, arg1: bigint): Promise<Array<TransactionWithDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentTransactions(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentTransactions(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Icrc1TransactionWithId_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Icrc1TransactionWithId): Icrc1TransactionWithId {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Icrc1Transaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Icrc1Transaction): Icrc1Transaction {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionOperation_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionOperation): TransactionOperation {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionWithDetail_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionWithDetail): TransactionWithDetail {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transaction_type: string;
    transaction: _Transaction;
    network: string;
    amount_adjusted: number;
    transfer_to: [] | [Principal];
    value_usd: number;
    augmented_memo: string;
    amount: bigint;
    transfer_from: [] | [Principal];
}): {
    transaction_type: string;
    transaction: Transaction;
    network: string;
    amount_adjusted: number;
    transfer_to?: Principal;
    value_usd: number;
    augmented_memo: string;
    amount: bigint;
    transfer_from?: Principal;
} {
    return {
        transaction_type: value.transaction_type,
        transaction: from_candid_Transaction_n16(_uploadFile, _downloadFile, value.transaction),
        network: value.network,
        amount_adjusted: value.amount_adjusted,
        transfer_to: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.transfer_to)),
        value_usd: value.value_usd,
        augmented_memo: value.augmented_memo,
        amount: value.amount,
        transfer_from: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.transfer_from))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memo: string;
    operation: _TransactionOperation;
    timestamp: bigint;
    index: bigint;
}): {
    memo: string;
    operation: TransactionOperation;
    timestamp: bigint;
    index: bigint;
} {
    return {
        memo: value.memo,
        operation: from_candid_TransactionOperation_n18(_uploadFile, _downloadFile, value.operation),
        timestamp: value.timestamp,
        index: value.index
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transaction: _Icrc1Transaction;
}): {
    id: bigint;
    transaction: Icrc1Transaction;
} {
    return {
        id: value.id,
        transaction: from_candid_Icrc1Transaction_n8(_uploadFile, _downloadFile, value.transaction)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: [] | [Uint8Array];
    fee: [] | [bigint];
    from: [] | [Uint8Array];
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    to?: Uint8Array;
    fee?: bigint;
    from?: Uint8Array;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        to: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.to)),
        fee: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.fee)),
        from: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.from)),
        memo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    burn: _BurnOperation;
} | {
    mint: _MintOperation;
} | {
    transfer: _TransferOperation;
}): {
    __kind__: "burn";
    burn: BurnOperation;
} | {
    __kind__: "mint";
    mint: MintOperation;
} | {
    __kind__: "transfer";
    transfer: TransferOperation;
} {
    return "burn" in value ? {
        __kind__: "burn",
        burn: value.burn
    } : "mint" in value ? {
        __kind__: "mint",
        mint: value.mint
    } : "transfer" in value ? {
        __kind__: "transfer",
        transfer: value.transfer
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionWithDetail>): Array<TransactionWithDetail> {
    return value.map((x)=>from_candid_TransactionWithDetail_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Icrc1TransactionWithId>): Array<Icrc1TransactionWithId> {
    return value.map((x)=>from_candid_Icrc1TransactionWithId_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Icrc1TransactionWithId_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Icrc1TransactionWithId): _Icrc1TransactionWithId {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Icrc1Transaction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Icrc1Transaction): _Icrc1Transaction {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transaction: Icrc1Transaction;
}): {
    id: bigint;
    transaction: _Icrc1Transaction;
} {
    return {
        id: value.id,
        transaction: to_candid_Icrc1Transaction_n3(_uploadFile, _downloadFile, value.transaction)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to?: Uint8Array;
    fee?: bigint;
    from?: Uint8Array;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}): {
    to: [] | [Uint8Array];
    fee: [] | [bigint];
    from: [] | [Uint8Array];
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
} {
    return {
        to: value.to ? candid_some(value.to) : candid_none(),
        fee: value.fee ? candid_some(value.fee) : candid_none(),
        from: value.from ? candid_some(value.from) : candid_none(),
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none(),
        amount: value.amount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
