/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BurnOperation { 'from' : Uint8Array, 'amount' : bigint }
export interface Icrc1Transaction {
  'to' : [] | [Uint8Array],
  'fee' : [] | [bigint],
  'from' : [] | [Uint8Array],
  'memo' : [] | [Uint8Array],
  'created_at_time' : [] | [bigint],
  'amount' : bigint,
}
export interface Icrc1TransactionWithId {
  'id' : bigint,
  'transaction' : Icrc1Transaction,
}
export interface MintOperation { 'to' : Uint8Array, 'amount' : bigint }
export interface Transaction {
  'memo' : string,
  'operation' : TransactionOperation,
  'timestamp' : bigint,
  'index' : bigint,
}
export type TransactionOperation = { 'burn' : BurnOperation } |
  { 'mint' : MintOperation } |
  { 'transfer' : TransferOperation };
export interface TransactionWithDetail {
  'transaction_type' : string,
  'transaction' : Transaction,
  'network' : string,
  'amount_adjusted' : number,
  'transfer_to' : [] | [Principal],
  'value_usd' : number,
  'augmented_memo' : string,
  'amount' : bigint,
  'transfer_from' : [] | [Principal],
}
export interface TransferOperation {
  'to' : Uint8Array,
  'fee' : bigint,
  'from' : Uint8Array,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'cacheIcTransaction' : ActorMethod<[Icrc1TransactionWithId], boolean>,
  'getAllIcTransactions' : ActorMethod<
    [bigint, boolean, string, string, boolean],
    Array<Icrc1TransactionWithId>
  >,
  'getRecentTransactions' : ActorMethod<
    [bigint, bigint],
    Array<TransactionWithDetail>
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];