/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Icrc1Transaction = IDL.Record({
  'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'fee' : IDL.Opt(IDL.Nat),
  'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Int),
  'amount' : IDL.Nat,
});
export const Icrc1TransactionWithId = IDL.Record({
  'id' : IDL.Nat,
  'transaction' : Icrc1Transaction,
});
export const BurnOperation = IDL.Record({
  'from' : IDL.Vec(IDL.Nat8),
  'amount' : IDL.Nat,
});
export const MintOperation = IDL.Record({
  'to' : IDL.Vec(IDL.Nat8),
  'amount' : IDL.Nat,
});
export const TransferOperation = IDL.Record({
  'to' : IDL.Vec(IDL.Nat8),
  'fee' : IDL.Nat,
  'from' : IDL.Vec(IDL.Nat8),
  'amount' : IDL.Nat,
});
export const TransactionOperation = IDL.Variant({
  'burn' : BurnOperation,
  'mint' : MintOperation,
  'transfer' : TransferOperation,
});
export const Transaction = IDL.Record({
  'memo' : IDL.Text,
  'operation' : TransactionOperation,
  'timestamp' : IDL.Int,
  'index' : IDL.Nat,
});
export const TransactionWithDetail = IDL.Record({
  'transaction_type' : IDL.Text,
  'transaction' : Transaction,
  'network' : IDL.Text,
  'amount_adjusted' : IDL.Float64,
  'transfer_to' : IDL.Opt(IDL.Principal),
  'value_usd' : IDL.Float64,
  'augmented_memo' : IDL.Text,
  'amount' : IDL.Nat,
  'transfer_from' : IDL.Opt(IDL.Principal),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'cacheIcTransaction' : IDL.Func(
      [Icrc1TransactionWithId],
      [IDL.Bool],
      ['query'],
    ),
  'getAllIcTransactions' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Vec(Icrc1TransactionWithId)],
      [],
    ),
  'getRecentTransactions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TransactionWithDetail)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Icrc1Transaction = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'fee' : IDL.Opt(IDL.Nat),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Int),
    'amount' : IDL.Nat,
  });
  const Icrc1TransactionWithId = IDL.Record({
    'id' : IDL.Nat,
    'transaction' : Icrc1Transaction,
  });
  const BurnOperation = IDL.Record({
    'from' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const MintOperation = IDL.Record({
    'to' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const TransferOperation = IDL.Record({
    'to' : IDL.Vec(IDL.Nat8),
    'fee' : IDL.Nat,
    'from' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const TransactionOperation = IDL.Variant({
    'burn' : BurnOperation,
    'mint' : MintOperation,
    'transfer' : TransferOperation,
  });
  const Transaction = IDL.Record({
    'memo' : IDL.Text,
    'operation' : TransactionOperation,
    'timestamp' : IDL.Int,
    'index' : IDL.Nat,
  });
  const TransactionWithDetail = IDL.Record({
    'transaction_type' : IDL.Text,
    'transaction' : Transaction,
    'network' : IDL.Text,
    'amount_adjusted' : IDL.Float64,
    'transfer_to' : IDL.Opt(IDL.Principal),
    'value_usd' : IDL.Float64,
    'augmented_memo' : IDL.Text,
    'amount' : IDL.Nat,
    'transfer_from' : IDL.Opt(IDL.Principal),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'cacheIcTransaction' : IDL.Func(
        [Icrc1TransactionWithId],
        [IDL.Bool],
        ['query'],
      ),
    'getAllIcTransactions' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Vec(Icrc1TransactionWithId)],
        [],
      ),
    'getRecentTransactions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TransactionWithDetail)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };